### ISSUE TITLE
Can't access Denon AVR-X1200W

### ISSUE THREAD

**Issue by steled** [ol-iver/denonavr#176]
Hi,

I'm trying to connect my Denon AVR-X1200W with Home Assistant via `denonavr` integration but getting the error from bottom.

My setup is:
- Home Assistant OS 5.9
- Home Assistant Supervisor: 2020.12.7

The Home Assistant is via LAN connected and the Receiver via WLAN. I can do `ping` as well as `curl` from Home Assistant to Receiver.

```
Logger: aiohttp.server
Source: components/denonavr/receiver.py:66
First occurred: 16:11:16 (1 occurrences)
Last logged: 16:11:16

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/denonavr/config_flow.py", line 106, in async_step_user
    return await self.async_step_connect()
  File "/usr/src/homeassistant/homeassistant/components/denonavr/config_flow.py", line 160, in async_step_connect
    if not await connect_denonavr.async_connect_receiver():
  File "/usr/src/homeassistant/homeassistant/components/denonavr/receiver.py", line 33, in async_connect_receiver
    if not await self._hass.async_add_executor_job(self.init_receiver_class):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/denonavr/receiver.py", line 66, in init_receiver_class
    self._receiver = denonavr.DenonAVR(
  File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 344, in __init__
    self.update()
  File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 524, in update
    self.ensure_configuration()
  File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 516, in ensure_configuration
    self._support_update_avr_2016 = support_avr_2016.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 644, in _update_avr_2016
    executor.submit(self._audyssey.update())
  File "/usr/local/lib/python3.8/site-packages/denonavr/audyssey.py", line 109, in update
    self.dynamiceq = bool(int(param.text))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

If you need more informations let me know.

**Comment by steled** [comment]
Problem was solved with Homeassistant Version 2020.12.2
