### ISSUE TITLE
M-CR510 support

### ISSUE THREAD

**Issue by kiddyfurby** [ol-iver/denonavr#199]
I get these in my home assistant logs
[DenonAVR] Input function NET is not known
[DenonAVR] Input function AUXD is not known
[DenonAVR] No mapping for input source 'AUX:Digital In'

I wish I could tell you which commit of denonavr but I only know I am on Home Assistant 2021.3.4

XML dumps:
[M-CR510 xml.zip](https://github.com/scarface-4711/denonavr/files/6249072/M-CR510.xml.zip)

**Comment by PollieKrismis** [comment]
My Marantz M-CR611 is also having similar issues.

I'm currently on Home Assistant v2021.4.6

I'm also not sure from which version these messages started appearing.

> 2021-05-01 14:03:58 ERROR (SyncWorker_0) [DenonAVR] Input function NET is not known
2021-05-01 14:04:08 ERROR (SyncWorker_4) [DenonAVR] Input function NET is not known
2021-05-01 14:04:18 ERROR (SyncWorker_0) [DenonAVR] Input function NET is not known
2021-05-01 14:04:38 WARNING (MainThread) [homeassistant.components.media_player] Updating denonavr media_player took longer than the scheduled update interval 0:00:10
2021-05-01 14:04:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.marantz_m_cr611 is taking over 10 seconds
2021-05-01 14:04:38 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.marantz_m_cr611 fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 292, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/denonavr/media_player.py", line 145, in update
self._receiver.update()
File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 571, in update
if self._update_avr() is not True:
File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 642, in _update_avr
if self._update_input_func_list():
File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 773, in _update_input_func_list
receiver_sources = self._get_receiver_sources()
File "/usr/local/lib/python3.8/site-packages/denonavr/denonavr.py", line 1217, in _get_receiver_sources
favorites = root.find(".//FavoriteStation")
UnboundLocalError: local variable 'root' referenced before assignment
2021-05-01 14:04:48 ERROR (SyncWorker_0) [DenonAVR] Input function NET is not known
2021-05-01 14:04:58 ERROR (SyncWorker_4) [DenonAVR] Input function NET is not known
2021-05-01 14:05:08 ERROR (SyncWorker_1) [DenonAVR] Input function NET is not known
2021-05-01 14:05:18 ERROR (SyncWorker_4) [DenonAVR] Input function NET is not known
2021-05-01 14:05:28 ERROR (SyncWorker_1) [DenonAVR] Input function NET is not known

**Comment by ol-iver** [comment]
Please wait for Home Assistant 2021.5 and check again. This library is completely redesigned. The new version will be included from that version on. Please reopen this issue, if you are facing similar issues then.
