### ISSUE TITLE
Questions for updating the docs for async

### ISSUE THREAD

**Issue by prcutler** [ol-iver/denonavr#219]
Hi,

I'm working on updating the README to include information about the new `async` commands (you can see a [WIP in my fork here](https://github.com/prcutler/denonavr/tree/readme-updates))

To avoid the coroutine was never awaited error, to turn the power off and on in the REPL looks like this:

```
>>> await d.async_power_on()
>>> d.async_power_on
>>> await d.async_update()
>>> d.async_update
>>> d.power
'ON'

>>> await d.async_power_off()
>>> d.async_power_off
>>> await d.async_update()
>>> d.async_update
>>> d.power
'OFF'

```

After I run d.async_power_on (or off) or d.async_update the REPL does print out everything I'd ever want to know about my AVR (this is just part of it).  Is this normal?  Are the above commands the right thing to run from the REPL?

Thanks for the confirmation - once I have that, I'll keep working on updating the docs so the usage examples work with `async`.

Paul

```
>>> d.async_update
<bound method DenonAVR.async_update of DenonAVR(_device=DenonAVRDeviceInfo(api=DenonAVRApi(host='192.168.1.119', port=8080, timeout=Timeout(connect=2.0, read=15.0, write=2.0, pool=2.0), _appcommand_update_tags=(AppCommandCmd(cmd_id='1', cmd_text='GetAllZonePowerStatus', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetAllZoneSource', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetRenameSource', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetDeletedSource', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetSurroundModeStatus', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetToneControl', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetAllZoneVolume', name=None, param_list=None, set_command=None, response_pattern=()), AppCommandCmd(cmd_id='1', cmd_text='GetAllZoneMuteStatus', name=None, param_list=None, set_command=None, response_pattern=())), _appcommand0300_update_tags=(AppCommandCmd(cmd_id='3', cmd_text=None, name='GetAudyssey', param_list=(AppCommandCmdParam(name='dynamiceq', text=''), AppCommandCmdParam(name='reflevoffset', text=''), AppCommandCmdParam(name='dynamicvol', text=''), AppCommandCmdParam(name='multeq', text='')), set_command=None, response_pattern=()),), async_client_getter=<function get_default_async_client at 0x109f20dc0>),

(Goes on with a lot more info)
```

**Comment by JPHutchins** [comment]
You should not need the second of each command. The long printout is what happens in REPL if you do not call the function with () and is not what you want (I think).

**Comment by prcutler** [comment]
Ok, thanks for the pointer.  I'm starting to get the hang of this.  

I'm going to leave this issue open in case I have any additional question for the readme.  I'll have a draft ready in the next day or two.

Thanks again!

--P

**Comment by prcutler** [comment]
Another question (sorry!):  How do I change volume via the async commands?

I've tried a couple of different ways in the REPL.  `d.async_update` doesn't seem to to do anything after passing `d.async_volume_up()` or `d.async_set_volume(-45)`

Code below.  Thanks in advance for pointing me in the right direction.

```
>>> await d.async_set_volume(-45)
>>> await d.async_update()
>>> d.volume
-31.5
>>> await d.async_volume_up()
>>> d.volume
-31.5
>>> await d.async_volume_up()
>>> await d.async_update()
>>> d.volume
-31.5
>>> await d.async_set_volume(-45)
>>> d.volume
-31.5
>>>

**Comment by prcutler** [comment]
Another question as I work on the docs:

What is the way to discover the DenonAVR on the network?  I can manually add a receiver using the IP, but the `denonavr.discover()` method raises a `Runtime Error`.  I tried with and without await in the REPL:

```
❯ python3 -m asyncio
asyncio REPL 3.9.5 (default, May  4 2021, 03:36:27)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import denonavr
>>> await denonavr.discover()
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/Users/prcutler/workspace/pi-dial/.venv/lib/python3.9/site-packages/denonavr/decorators.py", line 146, in wrapper
    return loop.run_until_complete(async_func(*args, **kwargs))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 580, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
>>> discovered_devices = denonavr.discover()
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/__main__.py", line 34, in callback
    coro = func()
  File "<console>", line 1, in <module>
  File "/Users/prcutler/workspace/pi-dial/.venv/lib/python3.9/site-packages/denonavr/decorators.py", line 146, in wrapper
    return loop.run_until_complete(async_func(*args, **kwargs))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 580, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
>>>
```

**Comment by ol-iver** [comment]
thanks for updating the README 👍 
`denonavr.discover()` is starting an own eventloop. That's why you cannot await it. However, `await denonavr.async_discover()` should work with a running event loop.

**Comment by prcutler** [comment]
Thanks for merging the Readme updates.  Closing this issue.
