### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by deiger** [ol-iver/denonavr#315]
For some reason, frequently the integration fails to communicate with the AVR, and I the log is spammed with the following errors:
```
2024-11-11 09:02:02.514 ERROR (MainThread) [denonavr.api] 10.0.0.20: Unexpected exception on telnet reconnect
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/denonavr/api.py", line 577, in _async_reconnect
    await self._async_establish_connection()
  File "/usr/local/lib/python3.12/site-packages/denonavr/api.py", line 490, in _async_establish_connection
    await self.async_send_commands(
  File "/usr/local/lib/python3.12/site-packages/denonavr/api.py", line 767, in async_send_commands
    await self._async_send_command(command, skip_confirmation=skip_confirmation)
  File "/usr/local/lib/python3.12/site-packages/denonavr/api.py", line 744, in _async_send_command
    raise AvrProcessingError(
denonavr.exceptions.AvrProcessingError: Error sending command Z3MU?. Telnet connected: True, Connection healthy: False
```

Worse yet, it appears that as a result, the integration repeatedly calls `asyncio.create_task` in [DenonAVRTelnetApi._handle_disconnected](../blob/c76907fb91216915da8db75556de4ff284c26060/denonavr/api.py#L609), and these tasks linger until the host is OOM.

**Comment by deiger** [comment]
This is the graph of HA's RAM usage, before disabling the `denonavr` integration (the mostly flat time yesterday was when the integration managed to connect to the AVR):
<img width="536" alt="image" src="https://github.com/user-attachments/assets/aac0b66f-1ec3-4df6-9c66-6c2b7c716385">

**Comment by ol-iver** [comment]
Apparently, the connection to your receiver breaks while it is still reconnecting and refreshing its state. This leads to another reconnect task while the old one is still running.
With #316 there should be only one reconnect task at the same time.

**Comment by deiger** [comment]
Thanks!

**Comment by deiger** [comment]
Could you please create a new release with this change?

**Comment by ol-iver** [comment]
done 🙂
