### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by aveach** [ol-iver/denonavr#6]
Installed denonavr using pip and get this ImportError (even after using pip to install parse as well):
```$ sudo pip install --use-wheel denonavr 
The directory '/Users/allen/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/allen/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: denonavr in /Library/Python/2.7/site-packages/denonavr-0.3.1-py2.7.egg
Requirement already satisfied: requests in /Library/Python/2.7/site-packages (from denonavr)

$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import denonavr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/denonavr-0.3.1-py2.7.egg/denonavr/__init__.py", line 15, in <module>
    from . import ssdp
  File "/Library/Python/2.7/site-packages/denonavr-0.3.1-py2.7.egg/denonavr/ssdp.py", line 13, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
>>> 
```

**Comment by ol-iver** [comment]
hej @swbooking,
unfortunately this library is not working with python 2.7, because it contains modules which were not available in this version. you'll need python 3.4 and higher.
cheers,
oliver
